# Generated by Django 4.0.2 on 2022-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0011_alter_extendeduser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile-pictures/user_icon.png', null=True, upload_to='profile-pictures/'),
        ),
    ]
